# yaml-language-server: $schema=experiment.schema.json
experiment: HP-Search
version: 1
n_trials: 30
optuna:
  sampler: 
    type: TPE
    n_startup_trials: 10

log_model: false
---
# yaml-language-server: $schema=config.schema.json
epoch: 250
lr: 1e-4~1e-2
batch_size: 3:3:12
topo_losses_delay: 10