# yaml-language-server: $schema=experiment.schema.json
experiment: HP-Search
version: 1
n_trials: 32
optuna:
  sampler: 
    type: TPE
    n_startup_trials: 12
  pruner:
    type: Median
    n_startup_trials: 12

log_model: false
progress_bar: false
---
# yaml-language-server: $schema=config.schema.json
epoch: 200
lr: 1e-4~1e-2
batch_size: 2:4:14
topo_losses_delay: 10