# yaml-language-server: $schema=experiment.schema.json
project: Topo-GNN
experiment: HP-Search
version: 2
tag: hp-search
n_trials: 20
optuna:
  direction: maximize
  sampler:
    type: GP
    n_startup_trials: 6
  pruner:
    type: Median
    n_startup_trials: 6

log_model: false
parameters_grid: 
  # - bipole-long: 
  #     archi: InstNorm Conv64x8-DropOut InstNorm Conv128x8-DropOut Conv256x4 Conv128x8 Conv256x4 Conv128x8 Conv256x4 Conv512x2
  #     bipole: true
  - bipole-short: 
      archi: InstNorm Conv64x8-DropOut InstNorm Conv128x8 Conv256x4 Conv512x2
      bipole: true
  - simple-long: 
      archi: InstNorm Conv64x8-DropOut InstNorm Conv128x8-DropOut Conv256x4 Conv128x8 Conv256x4 Conv128x8 Conv256x4 Conv512x2
      bipole: false
  - simple-short: 
      archi: InstNorm Conv64x8-DropOut InstNorm Conv128x8 Conv256x4 Conv512x2
      bipole: false
---
# yaml-language-server: $schema=config.schema.json
epoch: 200
lr: 5e-4~15e-4
batch_size: 20 
model:
  gcn:
    bipolar_node: $bipole
    architecture: $archi
